R2API/ReflectionCache.cs
=> More useful reflection cache

R2API/EntityAPI.cs, R2API/Hooks.cs, R2API/R2API.cs
Add checking for incompatible assemblies
Add EntityState hook for proper EntityState deserialization from outside assemblies
=> Add checking for incompatible assemblies

R2API/EntityAPI.cs, R2API/R2API.csproj, R2API/ReflectionCache.cs, R2API/Utils.cs
Add caching to existing reflection value methods
=> Fix caching API and entity api

.editorconfig, R2API/AssetAPI.cs, R2API/EntityAPI.cs, R2API/Hooks.cs, R2API/ILHelper.cs, R2API/InventoryAPI.cs, R2API/ItemAPI.cs, R2API/ItemDropAPI.cs, R2API/Notification.cs, R2API/PlayerAPI.cs, R2API/R2API.cs, R2API/ReflectionCache.cs, R2API/SurvivorAPI.cs, R2API/Utils.cs
K&R is my preferred brace style, if you would rather not have it, i can change the brace style no problem.
=> Reformat + Added EditorConfig

R2API/EntityAPI.cs, R2API/InventoryAPI.cs, R2API/ItemDropAPI.cs, R2API/Notification.cs, R2API/ReflectionCache.cs, R2API/SurvivorAPI.cs, R2API/Utils.cs
Instantiate with parameters, cached nestedTypes, reworked calls to
GetMethodCached.
Changed internal reflection to use cache.
=> ReflectionCache, Utils.Reflection extended, using Cached Reflection internally

R2API/CustomProcChain.cs, R2API/DefaultCustomEffect.cs, R2API/EffectAPI.cs, R2API/Hooks.cs, R2API/ItemAPI.cs, R2API/PlayerAPI.cs
Fulfill Issue :
#18 - Allow item to add any stats and any  onHit Effect, even customs ones
#13 - Modder can either ignore previous recalculate or update over them, added priority and some priority value to help developer choose the right one, added a Override flag, but unused for now
=> Fusing ModRecalculate 1.0.0 into R2API

R2API.MonoMod/SurvivorAPI.cs, R2API/AssetAPI.cs, R2API/EntityAPI.cs, R2API/InventoryAPI.cs, R2API/ItemAPI.cs, R2API/ItemDropAPI.cs, R2API/LobbyConfigAPI.cs, R2API/PlayerAPI.cs, R2API/R2API.cs, R2API/R2API.csproj, R2API/SurvivorAPI.cs, R2API/Utils/ILHelper.cs, R2API/Utils/Reflection.cs
=> Experimental

R2API/Hooks.cs, R2API/ItemDropAPI.cs, R2API/R2API.cs
+ Create logic for calculating lockbox loot.
=> Refactor ItemDropAPI, add smarter logic for determining chests

R2API/LobbyConfigAPI.cs
New wrapper class for CategoryDef, marked several methods as obsolete, reworked hooks.
=> New LobbyConfigAPI

R2API/ItemDropAPI.cs, R2API/R2API.cs
Let's not forget the gamebuild this time, tech-support is hard enough as it is.
=> Updates gamebuild number and fixes cloaked chests

R2API/SurvivorAPI.cs
Updated survivor api to interface with the new catalog features added in recent patch.
Some functionality was removed, but this is tested and works. (needs refs updated to build)
I'm sorry my code is so messy.
=> SurvivorAPI fixes

R2API/DirectorAPIexternal.cs, R2API/DirectorAPIhelpers.cs, R2API/DirectorAPIinternal.cs, R2API/EffectAPI.cs, R2API/OrbAPI.cs, R2API/PrefabAPI.cs, R2API/SkillAPI.cs, R2API/SkinAPI.cs
Added a DirectorAPI, PrefabAPI, OrbAPI, SkinAPI, SkillAPI, and EffectAPI.
All are created from helper functions I use throughout my mods.
Not 100% certain if there is anything special that needs to happen to get them to work as modules, but I did what I could based on other modules.
=> DirectorAPI, PrefabAPI, OrbAPI, SkinAPI, SkillAPI, EffectAPI

R2API/AssetAPI.cs, R2API/DirectorAPIexternal.cs, R2API/DirectorAPIhelpers.cs, R2API/DirectorAPIinternal.cs, R2API/EffectAPI.cs, R2API/OrbAPI.cs, R2API/PrefabAPI.cs, R2API/SkillAPI.cs, R2API/SkinAPI.cs
Basically:
Public events now start with capitals
Used `int`, `string` and `short` instead of `Int32`, `String`, `Int16`
removed unnecessary usings
added usings to unfully qualify some types.
=> Unify coding style new APIs

R2API/ItemDropAPI.cs
Fixes issue where lunar scavengers would not drop lunar coins.
=> Add scavenger support to ItemDropAPI

R2API.sln, R2API/LoadoutAPI.cs
Forgot to build for release when I tested :(
=> Fix to an access issue in LoadoutAPI

R2API/ModListAPI.cs, R2API/R2API.cs
Fix and disable ModListAPI for now until manifest v2 hit
=> Fix and disable ModListAPI for now

R2API/Utils/DirectMessage.cs
"If you can figure out how to convert a networkuser into a NetworkConnection, include it in r2api pls."
=> method of converting NetworkUser to NetworkConnection

R2API/ItemAPI.cs, README.md
=> Add ability to define Model specific IDRs for custom items

R2API/R2API.cs, R2API/Utils/CommandHelper.cs
Fix #123 and add debug logging to know which assembly is owning which hook
=> Fix #123 and more debug logging

R2API/LobbyConfigAPI.cs, R2API/R2API.cs
Fixes LobbyConfigAPI error (method name changed)
Make sure quickplay button is disabled (Hopoo forgot to add back the script that was disabling it for modded)
=> Update for latest game update.

R2API/BuffAPI.cs, R2API/EliteAPI.cs, R2API/ItemAPI.cs, R2API/LoadoutAPI.cs, R2API/Utils/CommandHelper.cs, R2API/Utils/Reflection.cs
Also removed safety hooks for user profiles as they are now useless since Hopoo added their own safety checks
=> Reflection fixes, BuffAPI and EliteAPI seperated from ItemAPI

R2API/ItemAPI.cs
Provided to you by the github website!
=> Fix Custom Equipment not displaying on bodies

R2API/DirectorAPIexternal.cs, R2API/DirectorAPIinternal.cs
Title. This doesn't fix any specific issue or anything, it's just nice to have.
=> Adds sky meadow to directorAPI

R2API/DirectorAPIexternal.cs, R2API/DirectorAPIinternal.cs
=> Fixed errors caused by my pull request

R2API/APIExtras/UnlockableAPIExtras.cs, R2API/UnlockablesAPI.cs
Very silly mistake on my part. Also fixed a case change I missed.
=> Fixed a last-minute typo in an IL hook.

R2API/EliteAPI.cs
Add what is needed for the API users to change the spawning of their custom elites
=> Elite API - Add spawn handling functionality

R2API/APIExtras/UnlockableAPIExtras.cs, R2API/UnlockablesAPI.cs
Leaving this as a draft for a little bit so it can be iterated on and tested more easily. You should be able to grab a build of this from azure.
=> Bugfix and feature for UnlockableAPI

.editorconfig, R2API.MonoMod/Attributes.cs, R2API.MonoMod/CatalogModHelperFix.cs, R2API.MonoMod/NoInlinePatches.cs, R2API.MonoMod/SearchableAttributeScanFix.cs, R2API/AssetPlus/Language.cs, R2API/DifficultyAPI.cs, R2API/DotAPI.cs, R2API/EntityAPI.cs, R2API/LobbyConfigAPI.cs, R2API/ModListAPI.cs, R2API/Notification.cs, R2API/UnbundledResourcesProvider.cs, R2API/Utils/APISubmodule.cs, R2API/Utils/ChatMessage.cs
Make missing xmldocs a message so that contributors can focus on real warnings.
=> Style, fix suggestions and warnings

.editorconfig, R2API.sln, R2API/AssetAPI.cs, R2API/AssetBundleResourcesProvider.cs, R2API/BuffAPI.cs, R2API/DifficultyAPI.cs, R2API/DirectorAPIexternal.cs, R2API/DirectorAPIhelpers.cs, R2API/DirectorAPIinternal.cs, R2API/DotAPI.cs
adds a significant number of xmldocs
=> xmldocs submodules A-D

R2API/DifficultyAPI.cs
But also allow people to use positive ones if they want.
=> Use Negative Based Indicii for custom difficulties by default

.gitmodules
Still need @tristanmcpherson  to add these to automated builds.
Removes the need for running hookgen manually
Allows us to remove Monomod.Loader dependency when ready
=> Add patchers to R2API package

R2API/LanguageAPI.cs
Rewrote LanguageAPI to be shorter and with less complexity
=> Rewrote LanguageAPI

R2API/SoundAPI.cs
If sound bank loading failed `Load` method tries to remove the sound bank from `SoundBanks.soundBanks` list. But `Load` is called inside foreach loop that iterates through `SoundBanks.soundBanks` list. So, if loading is failed an exception will be thrown because you can't remove an element from the list while iterating it. 
There is a fix for that.
=> Fix for sound banks loading

R2API/SurvivorAPI.cs
fix https://github.com/risk-of-thunder/R2API/issues/260
we still want to print all the added survivors at once, so that it show nicely in the log
=> fix useless list creation

R2API/DotAPI.cs
Bunch of stuff that I missed when doing the first pass.
=> Fix DotAPI

R2API/EliteAPI.cs
Bunch of stuff that I missed when doing the first pass.
=> Fix EliteAPI

R2API/Utils/NetworkCompatibility.cs
Made registration to network mod list ignore mods that don't depend on R2API.
Mods that do depend on R2API are still registered if they don't have `NetworkCompatibility` attribute
=> #268 opt-in/opt-out NetworkCompatibility

R2API/EliteAPI.cs, R2API/R2API.cs, R2API/SceneAssetAPI.cs
the FixEliteAPI commit is already merged, not sure why its still showing
=> Fix SceneAssetAPI for current patch

R2API/DirectorAPIexternal.cs, R2API/DirectorAPIinternal.cs
=> [DirectorAPI] Added missing scenes

R2API/DifficultyAPI.cs
Once merged I'll update DifficultyAPI Wiki
=> DifficultyAPI - AddDifficulty overload accepts Sprite as Icon

R2API/SoundAPI.cs, README.md
Add a class called SoundAPI.Music 
Associated r2wiki tutorial linked in the xml doc : 
https://github.com/risk-of-thunder/R2Wiki/wiki/Custom-Music---WWise
=> Extend SoundAPI for adding custom music to stages

R2API/SoundAPI.cs
No reason to allocate new space just to copy it from somewhere else when we can use the original without the copy
=> Remove unnecessary reallocation of array in SoundAPI

.github/workflows/release.yml
=> Tentative fix GitVersion_SemVer parsing

R2API/Utils/Reflection.cs
fix https://github.com/risk-of-thunder/R2API/issues/293
=> remove unused code from reflection class

R2API/Networking/Interfaces/INetCommand.cs, R2API/Networking/Interfaces/INetMessage.cs, R2API/Networking/Interfaces/INetRequest.cs, R2API/Networking/Interfaces/ISerializableObject.cs, R2API/Networking/NetworkDestination.cs, R2API/Networking/NetworkingAPI.cs, README.md
Add docs and fix https://github.com/risk-of-thunder/R2API/issues/218
=> NetworkAPI Doc and add a way to send message to specific connection

R2API/Utils/Reflection.cs
Check if the return type and set type is correct for a given field / property when getting / setting its value 
The test TestReflectionWrongFieldType wasnt throwing the expected exception for some reason on mono.
=> Check reflection types when getting / setting values

R2API/R2API.csproj, R2API/SoundAPI.cs, R2API/Utils/EmbeddedResources.cs
Based on the history of #320, either merge that one or this one
=> Allocation free loading of embedded soundbanks

R2API/DotAPI.cs, README.md
=> publicize DotAPI things

R2API/ContentManagement/R2APIContentManager.cs
Decided to add a Dictionary of ContentPack to assembly for ease of getting the assembly that's tied to the content pack.
regardless, i've also added properties to ManagedSerializableContentPack and ManagedReadOnlyContentPack that ties the SCP or  CP to an Assembly.
=> Cache the Ties between Assembly and ContentPack

R2API.Test/Tests/ReflectionTests.cs, R2API/ArtifactCodeAPI.cs, R2API/ContentManagement/R2APIContentManager.cs, R2API/DotAPI.cs, R2API/EliteAPI.cs, R2API/R2API.cs, R2API/ScriptableObjects/ArtifactCode.cs, R2API/ScriptableObjects/R2APISerializableContentPack.cs, R2API/Tweaks/ILLine.cs, R2API/UnlockableAPI.cs
- Fix ContentManager name fixing that was relying on LoadRoR2ContentEarly
- Moved needed global vanilla fixes to RoR2BepinexPack
- small doc improvements
=> Fix ContentManager name fixes, move stuff to RoR2BepinexPack

R2API/ContentManagement/R2APIContentManager.cs
This version will prioritize not enumerating types, but will fall back to doing so in cases where plugins aren't in the dictionary (ScriptEngine). Will finally fall back to just using the assembly name as an absolute last resort
=> Fix getting BepInPlugin name for content packs

R2API.Test/Tests/ConCommandTests/DirectorTests.cs, R2API/Director/DirectorAPIexternal.cs, R2API/Director/DirectorAPIhelpers.cs, R2API/Director/DirectorAPIinternal.cs
- Port stages that were still using the old spawning system to the new one, this effectively break again the methods but the API overall is now much easier to use than before.
- Fix null exceptions that could occur within the Simulacrum game mode.
=> Fix directorapi

R2API/DamageAPI.cs, R2API/DotAPI.cs, R2API/LanguageAPI.cs, R2API/R2API.cs, R2API/R2API.csproj, R2API/Utils/ManualLogSourceExtension.cs, README.md
Addressed issues #395, #388.
Fixed LanguageAPI, now ignoring case for language name, the same as the game.
=> Various fixes

R2API.Legacy/README.md
TS wants UTF8 encoding for README
=> Fix CI (continued)

R2API.Core/README.md, R2API.Core/Utils/NetworkCompatibility.cs, R2API.Core/thunderstore.toml, R2API.Networking/NetworkingPlugin.cs, R2API.Networking/README.md, R2API.Networking/thunderstore.toml
=> Moved NetworkCompatibility to Core module

R2API.Core/R2API.cs, R2API.Core/README.md, R2API.Core/thunderstore.toml, R2API.Networking/NetworkingPlugin.cs, R2API.Networking/README.md, R2API.Networking/thunderstore.toml
Oops, forgot about initialization in #444
=> Moved NetworkCompatibility initialization to Core

.github/workflows/main.yml, .github/workflows/release.yml
https://github.com/dotnet/sdk/issues/30624#issuecomment-1432118204
=> Fix CI breaking due to a breaking change introduced from a patch of the dotnet sdk

R2API.Core/README.md, R2API.Core/Utils/CompressedFlagArrayUtilities.cs, R2API.Core/thunderstore.toml
And that is why you write tests, kids. Which, to be fair, I did, but I forgot make tests for writing with < 8 and < 64 values =(
=> Fix CompressedFlagArrayUtilities writing for < 64 values

.gitignore, R2API.Difficulty/DifficultyAPI.cs, R2API.Difficulty/README.md, R2API.Difficulty/thunderstore.toml
=> DifficultyAPI: First added custom difficulty get skipped from rule catalog init due to a off by one error

R2API.SceneAsset/README.md, R2API.SceneAsset/SceneAssetAPI.cs, R2API.SceneAsset/thunderstore.toml, R2API.Test/Tests/AwakeTests/SceneAssetAPITests.cs
Was only happening if you were skipping intro and splash (done through config.cfg editing)
=> SceneAsset: Fix the game potentially not going past the splash / intro due to scene madness.

BuildCI/Program.cs, R2API.Core/R2API.cs, R2API.Core/README.md, R2API.Core/Utils/Reflection.cs, R2API.Core/thunderstore.toml, R2API.Test/R2APITest.cs, R2API.Test/Tests/AwakeTests/ReflectionTests.cs
also some local debug  setup improvments
=> Remove DeclareOnly binding flag, shouldnt be breaking

R2API.Director/DirectorAPIexternal.cs, R2API.Director/README.md, R2API.Director/thunderstore.toml
Fixes a type mismatch on the DirectorAPI's DirectorCardHolder.
@xiaoxiao921 said it's ok to do the breaking change so i blame him if anything wrong happens 😛
=> fix type mismatch

R2API.Addressables/AddressReferencedAssets/AddressReferencedAsset.cs, R2API.Addressables/AddressReferencedAssets/AddressReferencedEquipmentDef.cs, R2API.Addressables/R2API.Addressables.csproj, R2API.Addressables/README.md, R2API.Addressables/thunderstore.toml
=> Fixed typo on R2API.Addressables constructor

R2API.ContentManagement/ContentManagementPlugin.cs, R2API.ContentManagement/README.md, R2API.ContentManagement/thunderstore.toml
Adds the searchable attribute,fixing behavior that counts on SystemInitializer to work.
=> ContentManagement: Searchable Opt-In Attribute

R2API.ContentManagement/ContentAddition.cs, R2API.ContentManagement/README.md, R2API.ContentManagement/thunderstore.toml
Fixes #494
Implemented as mentioned in https://github.com/risk-of-thunder/R2API/issues/511#issuecomment-1869062787
While this is technically more work,it seemed to not have any noticeable effect on my boot times.
_However_,my experience is mostly bottlenecked by disk speed,so someone on faster drives should test it out and compare the Game Content Load times printed to log.
=>  ContentManagement: Climb Stack for contentpack asm

R2API.Director/DirectorAPIexternal.cs
=> DirectorAPI: StageSerde struct

R2API.Core/README.md, R2API.Core/Utils/SystemInitializerInjector.cs, R2API.Core/thunderstore.toml
Updated SystemInitializerInjector for new SystemInitializer
=> Fix SystemInitializerInjector again

R2API.Animations/AnimatorModifications.cs, R2API.Animations/ModificationsBundleCreator.cs, R2API.Animations/README.md, R2API.Animations/thunderstore.toml
A little breaking change while API is not used by released mods
=> [AnimationsAPI] Change values for NewStates and NewTransitions to lists

R2API.DamageType/DamageAPI.cs, R2API.DamageType/README.md, R2API.DamageType/thunderstore.toml
=> [DamageAPI] fix FireProjectileInfo.damageTypeOverride not being applied

R2API.CharacterBody.Interop/CharacterBodyInterop.cs, R2API.CharacterBody.Interop/R2API.CharacterBody.Interop.csproj, R2API.CharacterBody.Patcher/CharacterBodyPatcher.cs, R2API.CharacterBody.Patcher/R2API.CharacterBody.Patcher.csproj, R2API.CharacterBody/CharacterBodyAPI.cs, R2API.CharacterBody/CharacterBodyPlugin.cs, R2API.CharacterBody/R2API.CharacterBody.csproj, R2API.CharacterBody/README.md, R2API.CharacterBody/thunderstore.toml, R2API.Core/AssemblyInfo.cs, R2API.Core/R2API.cs, R2API.sln, RoR2.Patched/CharacterBody.cs
Video Preview
https://github.com/user-attachments/assets/a131e93c-9284-4e6e-911d-dd1b902042ed
=> R2API.CharacterBody module addition with Modded Body Flags feature
