risk-of-thunder/R2API

- R2API/EntityAPI.cs
- R2API/ReflectionCache.cs
Rename cached reflection layer methods, more work to be done on this soon
Fix access bug with EntityAPI hook that was recently added
> Fix entity api wrong access, rename reflection cache methods

- R2API.MonoMod/R2API.MonoMod.csproj
- R2API.MonoMod/SurvivorAPI.cs
- R2API.sln
- R2API/SurvivorAPI.cs
Complete rework of `SurvivorAPI.ReconstructSurvivors`, addition of `SurvivorAPI.AddSurvivor` and `SurvivorAPI.AddSurvivorOnReady` for hassle-free insertion of survivors, addition of a MonoMod component instead of a hook because `RoR2.SurvivorCatalog.GetSurvivorDef` gets inlined.
> Survivor API rework

- R2API/SurvivorAPI.cs
1.The SurvivorCatalog now has 2 new arrays : 
`SurvivorIndex[] bodyIndexToSurvivorIndex`
`int[] survivorIndexToBodyIndex`
Making sure they are updated each time a new survivor is added in `ReconstructSurvivors()`.
2. Adding the Loader SurvivorDef
> Fix the SurvivorAPI for the Skills 2.0 Game Update

- R2API/Utils/CommandHelper.cs
Detects fields derived from `RoR2.Convar.BaseConvar` in an assembly and adds it to the console.
The assembly itself needs to call `RegisterConVars` anytime after `initConvars` happens in the game.
> Adds the possibility for mods to register convars

- R2API/Utils/CommandHelper.cs
Call `R2Api.CommandHelper.AddToConsoleWhenReady()` in your mod at any point to have your convars and concommands added to the console.
Keeps backwards compatibility with mods that used the old method, while politely warning them the method is obsolete.
Added XML docs to the only public methods.
Class is now a **submodule** and may need renaming or be moved out of utils. I'll leave that to maintainers' decision.
> Ease the use of CommandHelper

- R2API/Utils/CommandHelper.cs
Current version breaks when building for Release, I did not account for this when I submitted my previous PR.
Switching to reflection instead of just using a private method works.
Thanks @paddywaan for reporting this.
> use reflection for private method

- R2API.MonoMod/CatalogModHelperFix.cs
The CatalogModHelper currently sort each new Modded Entries by their name, which mess up our manual retrieval of their index, we don't need it : but because of that, we have also to make sure people playing with the same set of mods have the same plugins loading orders (folder structure may change it). Something that the next BepinEx release on thunderstore will take care of
> Disabled modded entries sorting

- R2API.MonoMod/NoInlinePatches.cs
- R2API/DifficultyAPI.cs
Used for adding difficulties. This design can probably be generalized to all rule sections.
Because the Difficulty array is in static class as a static readonly array, modifying it is hard. Future patches might change this to a nonreadonly array, as said by Ghor. I'll keep an eye out.
Use:
```csharp
DifficultyDef myDifficultyDef = new DifficultyDef(myScalingFactor /*(1f=drizzle,2f=rainstorm,3f=monsoon)*/, myNameToken, myIconPath, myDescriptionToken, hoverOverColor);
DifficultyIndex myDifficultyIndex = R2API.DifficultyAPI.AddDifficulty(myDifficultyDef);//pretend this is actual declared inside the valid scope
// Then at any point later you can 
if(Run.Instance && Run.Instance.selectedDifficulty == myDifficultyIndex)
{
//cool code that only happens in your difficulty here.
}
```
> Adds the DifficultyAPI

- R2API/Utils/ChatMessage.cs
A lot of things in game and in mods use the `UnityEngine.Color` class instead of `System.Drawing.Color`. Overloads for the former are added.
Backwards compatible.
> Add UnityEngine.Color overload for colored messages

- R2API.MonoMod/Attributes.cs
- R2API.MonoMod/Publicizer.cs
- R2API/R2API.cs
to make sure we keep vanilla clients aware that tehy are joining a modded lobby.
> add [mod] prefix to dedicated servers

- R2API/R2API.cs
- R2API/Utils/APISubmodule.cs
- Add a method that warn the users if the r2api monomod patch is missing.
- fix a bug where the submodules can be loaded twice if a user have a duplicate r2api.dll in their plugins/ folder
> Add Warning when monomod patch is missing

- R2API/ModlistAPI.cs
- R2API/R2API.cs
Switched to async await for network message handling. No longer needs static R2API ref for coroutines.
Fixed a bug with config file serialization that occured with some cases of custom bepinex typeconverters.
Edit: Also did quite a bit of stress testing on ModlistAPI.
> Fix/update for ModListAPI

- R2API/ItemAPI.cs
- R2API/R2API.cs
- README.md
* added internal event for R2API start.
* No longer runs on each charactermodel start, but only once on game start.
* Custom survivors may have definitions for custom items defined, and r2api no longer overwrites them if the custom item doesn't have it's own case for it.
> Allow custom survivors to define display rules for custom items & improve code quality of display rules

- R2API/R2API.cs
- R2API/SurvivorAPI.cs
Add a safety check for descriptionToken of custom survivors not having an Environement.NewLine, thus throwing an OutOfRange exception in the `CharacterSelectBarController.Build` method, breaking all other survivor mods after that
> Fix for the descriptionToken of custom survivors

- .gitmodules
- R2API/AssetPlus/Language.cs
- R2API/AssetPlus/assetplus.cs
- R2API/AssetPlus/font.cs
- R2API/AssetPlus/sound.cs
- R2API/FontAPI.cs
- R2API/LanguageAPI.cs
- R2API/SoundAPI.cs
- R2API/Utils/APISubmodule.cs
Also reworked LanguagePlus to no longer need to reload language, old functions now redirects to new functions
> Integrate assetplus into main repo and seperate it's components

- R2API/ItemDropAPI.cs
- README.md
This allows custom Items to drop from category chests.
But the question is why this hooks breaks everything in the first place.
> Fix category chests by removing hook

- R2API.MonoMod/R2API.MonoMod.csproj
- R2API.MonoMod/SearchableAttributeScanFix.cs
- README.md
This causes the preloader to crash when r2api is removed from the plugins folder.
This might fix rare cases in which 2 r2api.dlls are located in the plugin folder. Maybe.
> Fix r2api plugin dependency of MonoMod patcher file

- R2API/ItemAPI.cs
Unsafe names cause runreports to not be generated correctly, and might cause profile corruption.
Sort of fixes #145
> Prevent adding XML unsafe items.

- R2API/ItemAPI.cs
- R2API/ItemDropAPI.cs
Fixes: items removed from `Run.availableItems` and/or from `Run.available...DropList` (during a hook on `On.RoR2.Run.BuildDropTable`) still drop from chance shrines iff ItemDropAPI is loaded. This fix is performed by adding new public methods to remove items from the internal default drop tables (previously, only addition could be performed).
Fixes: calling `Run.instance.BuildDropTable()` mid-run causes duplicates of the default lists to be added, which in turn skews drop chances in favor of those items. This fix is performed by adding a new IsDefaults flag to PickupSelection. During all `DefaultItemDrops.AddDefault...Drops` methods, IsDefaults is set to true on all added PickupSelections; all existing entries with IsDefaults=true are removed before adding the new ones.
Adds overloads for …
> ItemDropAPI: Allow public removal of items from the default drop lists

- R2API/R2API.cs
To be specific, the changes to SurvivorAPI (https://github.com/risk-of-thunder/R2API/pull/162) made a method into standard hook. However, the old method was still being called by R2API's constructor, thus causing builds to fail. I've removed the line that called the method in my pull request.
> Removed a line in RoR2's constructor that caused R2API builds to fail.

- R2API.Test/UnbundledResourcesProviderTests.cs
- R2API/UnbundledResourcesProvider.cs
For context, the class RoR2.ItemDef has the field pickupIconPath which both pickupIconSprite and pickupIconTexture use to load their assets based on their type. Previously, UnbundledResourceProvider didn't track the stored types so it wasn't possible to handle this.
> Fixed being unable to have assets with the same path but different type in UnbundledResourceProvider.

- R2API.Test/UnbundledResourcesProviderTests.cs
- R2API/UnbundledResourcesProvider.cs
Context: Anytime UnbundledAssetProvider.Store is called using just a key instead of a full path, an additional "@" is appended to the modPrefix which breaks ResourcesAPI.ModResourcesLoad.
Fix: Enforce that modPrefix must have "@" at the start of its name so it can be removed from the ConvertToFullpath format string.
> Fixed bug with ConvertToFullpath by enforcing that ModPrefix start with @.

- R2API/R2API.cs
Tags will be client visible, meaning we don't have to enforce the title anymore.
> Remove "[MOD]" from server title

- R2API/ItemAPI.cs
- R2API/ItemDropAPI.cs
- R2API/Utils/NetworkCompatibility.cs
the NetworkCompatibilityHandler wasn't properly checking for the ManualNetworkRegistration attribute, now fixed
ItemDropAPI was allowing items with the WorldUnique tag to be on the drop tables, now fixed.
> Hotfix for the NetworkCompatibility handler and ItemDropAPI

- R2API/Utils/NetworkCompatibility.cs
- R2API/Utils/PluginScanner.cs
The plugin scanner now account for duplicate assemblies if end users have scuffed plugins folder.
It fixes an issue that can happen if an end user have duplicate assemblies in their plugins folder,
both assemblies would get added to the network mod list even if only one was used.
> More NetworkCompatibility hotfix

- R2API/Networking/NetworkingAPI.cs
Make Internal equivalents methods for NetworkingAPI so that SetHooks can register properly the types without throwing
> NetworkingAPI Initialization fix

- R2API/LanguageAPI.cs
Current implementation adds all languages to GenericTokens because of that, only last language will be stored.
I've fixed it so now tokens are added to specific languages (how it's described in the comment).
Also, the first available language will be added to generics, so that it will be used when no language-specific tokens found.
> [LanguageAPI] load from file fix

- R2API/EliteAPI.cs
- R2API/R2API.cs
- R2API/Utils/APISubmodule.cs
- R2API/Utils/NetworkCompatibility.cs
- R2API/Utils/PluginScanner.cs
- Fix an oob array exception with EliteAPI that was adding incorrectly custom elites of tier 2 and above.
-  Better display of missing mods for end users when a mod mismatch happens
- Better log message if the monomod patch of r2api is missing
- R2API now adds itself to the networked mod list for syncing purposes when NetworkingAPI is active (the message classes from that API could be different across r2api versions and cause problems for example)
- Fix a rare bug ( computer specific ? ) where the NetworkCompatiblityHandler wasnt correctly retrieving the arguments of the NetworkCompatibility attribute
- Better detection of duplicate assemblies that could be sitting in the plugins folder of an end user
> EliteAPI fix, NetworkCompatiblity fix and more

- R2API/Networking/Interfaces/INetCommand.cs
- R2API/Networking/Interfaces/INetMessage.cs
- R2API/Networking/Interfaces/INetRequest.cs
- R2API/Networking/NetworkingAPI.cs
Fixed a few bugs that allowed messages to be executed multiple times when sent from a client that was hosting.
> Fixed double sending bugs in NetworkAPI

- R2API/LanguageAPI.cs
LanguageOverlays provide a way to make temporary changes to language tokens without interfering directly with other mods. Conflicts are still resolved via order of addition (the last mod to change a token will have its changes apply); however, unlike the existing system, removal can be easily performed (after which the previous mod in the stack will take over). LanguageOverlays also take precedence over the existing system without replacing it entirely -- they're less performant, and would break compatibility if used as a replacement.
Changes made by this PR:
- Adds the class LanguageAPI.LanguageOverlay, the struct LanguageAPI.OverlayTokenData, and several public methods for registering new LanguageOverlays (which mirror the existing LanguageAPI.Add methods).
- Adds the public …
> LanguageAPI: implement LanguageOverlays

- R2API/Networking/Interfaces/INetCommand.cs
- R2API/Networking/Interfaces/INetMessage.cs
- R2API/Networking/Interfaces/INetRequest.cs
- R2API/Networking/NetworkingAPI.cs
- R2API/Utils/NetworkCompatibility.cs
- Reply / Request message types for networking api were causing a potential infinite loop : the NetworkServer would forward the request to its Client connection equivalent even though it already handled the request fine.
- NetworkCompatibility can throw if the scanned assembly is compiled against a different net standard version. R2API and all other plugins should be using 2.0 as it was the Unity backend is the closest to. With Cecil scanning this error cannot happen but it showed to be fragile. I'm still unsure how the scanning should be done, either with classic Reflection or Cecil, in case we want to go back the git commits still have the old version saved. For now the issue is minor and can be very easily fixed by the mod makers by simply switching their net standard version to match …
> Fix Reply/Request Messages for NetworkingAPI and minor NetworkCompatibility fix

- R2API/Networking/NetworkingAPI.cs
- R2API/SceneAssetAPI.cs
- Add `SceneAssetAPI` submodule that allow mod makers to retrieve assets that are not in the `Resources` folder and thus not easily accessible : Those are usally assets that are only available through the root game objects of a scene. The only way to retrieve those is to load the requested scenes additively on game start. Luckily we have an option to set them to be disabled when loaded so the game start speed is not really getting affected as much if they were being active.
Exemple Usage : 
```cs
SceneAssetAPI.AddAssetRequest(MoonSceneName, OnMoonSceneLoadedGetDropShip);
private static void OnMoonSceneLoadedGetDropShip(GameObject[] sceneRootGameObjects)
{
DropShipPrefab = sceneRootGameObjects[0].transform.Find(DropShipPath).gameObject.InstantiateClone(DropShipPrefabName);
}
```
- Also fix …
> Add SceneAssetAPI

- R2API/ItemAPI.cs
- R2API/ItemDropAPI.cs
- R2API/ItemDropAPI/Catalogue.cs
- R2API/ItemDropAPI/DropList.cs
- R2API/ItemDropAPI/DropOdds.cs
- R2API/ItemDropAPI/InteractableCalculator.cs
- R2API/MonsterItemsAPI.cs
For players, if an interactable cannot yield any items it will be prevented from spawning.
If an interactable cannot yield any items of a particular tier the selection weight for that tier will be 0.
For monsters if a particular tier cannot yield any valid items the selection weight for that tier will be 0.
Created functions for both ItemDropAPI and MonsterItemsAPI to handle adding and removing items from the drop list.
AddItemByTier and UnaddItemByTier to add items to tier lists.
RemoveItemByTier and UnremoveItemByTier to remove items from tier lists.
AddEquipmentByTier and UnaddEquipmentByTier to add equipment to tier lists.
RemoveEquipmentByTier and UnremoveEquipmentByTier to remove equipment from tier lists.
Refactored hooks for player items from ItemDropAPIFixes into ItemDropAPI. …
> Merged in ItemDropAPIFixes.

- R2API/InteractablesAPI.cs
- R2API/ItemDropAPI.cs
- R2API/ItemDropAPI/Catalogue.cs
- R2API/ItemDropAPI/DropList.cs
- R2API/ItemDropAPI/DropOdds.cs
- R2API/ItemDropAPI/InteractableCalculator.cs
Made scrap locating much more robust.
Added additional filtering when locating elite equipment.
Fixed special boss items not being added to the drop list by default.
Fixed Cleansing Pools being prevented from spawning.
> Added InteractablesAPI

- R2API/FontAPI.cs
- R2API/LanguageAPI.cs
- R2API/SoundAPI.cs
- R2API/Utils/APISubmodule.cs
it is implemented using a new step in InitStage that gets called if the submodule is not previously defined as a R2APISubmoduleDependency and should have the signature void func(out/ref bool)
> Adds a way for submodules to be able to check if they should be loaded

- R2API/Tweaks/ILLine.cs
Adds a submodule named ILLine that always loads (shouldload always gives true).
Based on [this mod](https://thunderstore.io/package/mistername/IlLine/) that makes it so on stack traces it tries to replace the 0 on the end with the IL offset of the instruction (inlining can cause this line number to not be correct).
useful for knowing where your code raises an exception
> Added ILLine submodule

- R2API/ItemDrop/Catalog.cs
- R2API/ItemDrop/DropList.cs
- R2API/ItemDrop/InteractableCalculator.cs
- R2API/ItemDropAPI.cs
- R2API/MonsterItemsAPI.cs
This should address the majority of the bugs that were passed on to me.
- Changed drop list operation lists so they are cleared each time they are used, as a stop gap measure so my other mods would be able to continue functioning normally. I know Rein's methods will make this redundant shortly.
- Drop lists should never be empty now and will always contain PickupIndex.none instead. This was for increased consistency, as previously these lists could sometimes contain PickupIndex.none and sometimes be empty, causing bugs.
- Added function to determine if a drop list only contained PickupIndex.none, this has been substituted in wherever a check was done previously to see if a drop list was empty.
- All world unique items are now stored in a list in Catalog and are no longer added to the …
> Bug fixes for ItemDropAPI and MonsterItemsAPI

- R2API/LoadoutAPI.cs
RoR sometimes lacks null checks. This is a kinda big problem with skins and `ProjectileGhostReplacementManager` because if any skin has `projectileGhostReplacements` equal to null it will throw an error.
This small change ensures that all arrays in `SkinDef` will be non-null.
> [LoadoutAPI] Using non null arrays for SkinDef

- R2API/ItemDrop/InteractableCalculator.cs
- R2API/ItemDropAPI.cs
Fixed subset chests dropping any item, regardless of subset.
Fixed question marks in multishops having an outline matching the tier of the hidden item instead of the tier of the multishop.
Fixed issue where a tier is disabled for subset chests when a pickup is available in multiple drop lists.
Fixed issue where scrap could cause an empty tier to be considered present.
> ItemDropAPI bug fixes

- R2API/Utils/DirectoryUtilities.cs
I'm currently working with ThunderKit and having some issues, which lead to printing folder structure to in log. And, since ThunderKit stores BepInEx not under a game folder (which is a totally valid way to do it), an important part of the folder structure was not printed.
This change ensures that BepInEx folder content is printed.
Now that I think about it, why print a game folder structure and not BepInEx in the first place, since there's nothing useful outside of the BepInEx folder.
> Printing BepInEx folder if it's not under Risk of Rain 2 folder

- R2API/R2API.cs
Some time ago I've reported a minor error in r2api channel in Discord. 
TL;DR;
When launching RoR with Unity debug build it throws an error in SoundAPI because Unity doesn't allow to call its API from MonoBehaviour's constructor (in this case it's `Application.isBatchMode`). 
Changing from constructor to Awake fixes the problem and doesn't make any difference for r2api loading logic.
Here's the link to a discussion about this error: https://discord.com/channels/562704639141740588/567836513078083584/800293856629358603
> Change `R2API` constructor to Awake

- R2API/LanguageAPI.cs
added a hook so RoR2.Language.TokenIsRegistered functions correctly with the languageAPI.
Only notes for the logbook called this function.
> Fixed notes in logbook

- R2API/ItemAPI.cs
- R2API/ItemDrop/Catalog.cs
- R2API/ItemDrop/DropList.cs
- R2API/ItemDrop/DropOdds.cs
Fixed a bug where all items and equipment are part of standard drop lists during the first run after the game is launched.
Fixed a bug where all custom special items are added to drop lists regardless of whether they are unlocked.
Discovered potential issue where custom special equipment will be added to drop lists regardless of whether it is unlocked but don't have a good solution.
> Drop list bug fixes

- R2API/ResourcesAPI.cs
Changed error messages to provide correct info on the error.
Added `return null` if a provider was not found, so there will be no NRE inside API itself.
> Resource API messages update and NRE fix

- Archived changelogs.md
- README.md
Started working on issue #255. For now, I've created a file with changelogs before 3.0.0 and added missing ones for 2.x.x versions. Now will work on readme and 3.0.0+ changelogs.
> Missing changelogs in readme

- R2API/LoadRoR2ContentEarly.cs
- R2API/R2API.cs
I was hard coding a GetMethod for an anonymous delegate, making it very unreliable once a new game patch hit
`RetrieveMethodThatInstantiateRoR2Content()` should hopefully fix it now
> Fix for new game patch

- R2API/DeployableAPI.cs
- README.md
Working on a custom character and needed to create my own deployable with a count limit. And `DeployableSlot` is just an enum with no way to add new slots. So I made this API to ensure mods that want to do the same thing won't conflict.
Very simple API with only one method to register a function to get deployable limit. Everything else regarding deployables seems to work as-is.
> Adding DeployableAPI

- R2API/Utils/NetworkCompatibility.cs
- README.md
Related conversation: https://discordapp.com/channels/562704639141740588/567836513078083584/841529389207650315
TL; DR;
Mods that used SoftDependency to R2API were in the middle ground where they are registered to the network and can't do anything about it.
This change excludes mods with SoftDependency from the network registration.
> NetworkCompatibility ingore mods with SoftDependency

- R2API/RecalculateStatsAPI.cs
This is more of a migration of TILER2's StatHook to R2API. I believe it's an amazing implementation given that it lets mod developers add a hook easily with their modifications. Another reason for this is so that there's a unified approach when dealing with RecalculateStats.
Big thanks to ThinkInvisible.
> Implement RecalculateStatsAPI, an API provided by TILER2

- R2API/R2API.cs
Addressing #278.
Having several buttons as default fallback won't cause any issues.
> Set Eclipse button as default fallback

- R2API/PrefabAPI.cs
- README.md
Related conversation: https://discord.com/channels/562704639141740588/567836513078083584/854006351696625715
TL;DR;
Using native offset was kinda dumb since it's offset in JIT-compiled code and most likely can differ on different PCs and/or OS.
This change makes that you are not able to register prefab with the same name in one method, but, I think, no one does that anyway.
Also added an overload to InstantiateClone to fix the ambiguity.
I think this should be published asap since it's a pretty big issue for multiplayer.
> Network registration fix

- R2API/ArtifactCodeAPI.cs
- R2API/ArtifactCodeScriptableObject.cs
- R2API/ScriptableObjects/ArtifactCode.cs
- README.md
Allows the creation of new Artifact codes to be used in the artifact portal found in sky meadow.
Works by storing an array of DialedActions and appending them to the Portal Dialer Controller instance of SkyMeadow on Awake.
There are 3 public classes
* `ArtifactCodeAPI`: Handles the overall storing and creation of new artifact codes
* `ArtifactCodeScriptableObject`: Allows the ease of creation of codes by simply inputting the Artifact Compound's values into a list. Works both for Code use and Editor use.
* `CompoundValues`: Contains the values of Vanilla Risk of Rain 2 Artifact Compounds (Empty, Square, Circle, Triangle and Diamond.)
The API works by mainly hooking into 2 methods inside the PortalDialerController class.
* `awake`: Reads through the list of ArtifactCodes (Composed by an …
> [Artifact Code API] Custom artifact codes for Bulwark's Ambry

- R2API/SoundAPI.cs
- README.md
This PR adds a way for developers to register `NetworkSoundEventDef` instances to the r2apiContentPack via the SoundAPI along with a few sanity checks for good measure.
Currently under `SoundAPI` there is not a way to add in sounds that are network ready. This utilizes the content pack system to register these at runtime under the R2API content pack which will then allow them to be used with RoR2's `EntitySoundManager` class.
Similar to `ItemAPI` or `ArtifactAPI`, there are two ways of properly adding a `NetworkSoundEventDef`.
1. `SoundAPI.AddNetworkedSoundEvent(NetworkedSoundEventDef? networkSoundEventDef)` - allows you to pass in your own `NetworkSoundEventDef` to SoundAPI and if it passes the sanity checks, into the r2apiContentPack.  Useful for when you want to save a reference to …
> Add NetworkSoundEventDef registration to SoundAPI

- R2API/UnlockableAPI.cs
for the first time ever
ability to pass in a BaseServerAchievement type to be tracked
obseleted the serverTracked parameter which wasn't actually accomplishing anything. Backwards compatible
> fixing server unlockables

- R2API/UnlockableAPI.cs
- README.md
Added support for created UnlockableDefs being passed into AddUnlockable, along with some overloads for compatibility. This should add support for ThunderKit workflows, which creates UnlockableDefs inside Unity directly and not in code.
> Premade UnlockableDefs in AddUnlockable

- R2API/ItemAPI.cs
ItemDef/EquipmentDef.pickupModelPrefab should have an ItemDisplay attached to them when they have ParentedPrefab display rules linked to them, otherwise the game method `CharacterModel.UpdateMaterials` will throw.
Not making it an error that doesnt add the items since  : 
- we have a hook already setup that doesnt make the game method throw and ultimately its only a minor visual issue in game.
- some mods wouldnt work anymore even if they are "fully working" gameplay wise
> Log bad item / equipment pickup models in console

- R2API/UnlockableAPI.cs
This pull request has the commits found in King Enderbrine's "Additional overloads for AddUnlockable" #317, Information on said parts can be found on his pull request.
The main improvement i've done to UnlockableAPI is in the form of the AddAchievement method, which allows the end user to add an already pre-made AchievementDef to the game.
This is mainly useful on systems where the Unlockables are done thru different methods outside of the default r2api one, such as in MSU's [MSUnlockableDef](https://github.com/TeamMoonstorm/MoonstormSharedUtils/blob/main/MSU/ScriptableObjects/MSUnlockableDef.cs) (Which handles the creation of the achievementDef automatically)
> UnlockableAPI Improvements

- R2API/SoundAPI.cs
The bool that was responsible for letting the vanilla music bank or not was not always properly synced.
Now check in Update to be always synced and simplify a lot the overall logic
this PR cancel https://github.com/risk-of-thunder/R2API/pull/318
> Fix MusicAPI

- R2API/ArtifactCodeAPI.cs
- R2API/ScriptableObjects/ArtifactCode.cs
After using the ArtifactCode scriptable object, while it works decently for creating the code from the usual VS method of mod creation, working with the scriptable object itself in the unity editor is a pain, this is due to the fact that the field that's show in the inspector is a list, and working with lists is difficult without a proper custom inspector (something that's outside of the realm of R2API for now i imagine)
Due to this, i've decided to do the following changes to the ArtifactCode scriptable object:
* Create 3 new fields of type Vector3Int
* Mark `List<int> ArtifactCompounds` as Obsolete, and mark it with the HideInInspector attribute (As the 3 new fields is supposed to replace it)
* Throw a warning when a code still has values in the ArtifactCompounds list, the code still …
> [ArtifactCodeAPI] Minor changes to the ArtifactCode scriptable object

- R2API/TempVisualEffectAPI.cs
- README.md
Allows for adding custom TemporaryVisualEffects (TVEs) to every CharacterBody spawned that functions the same as vanilla TVEs.
Use `TempVisualEffectAPI.AddTemporaryVisualEffect()` before `WhenContentPackLoaded` (usually in mod's `Awake()`) to add a custom TVE to a static List and Dictionary. Custom TVE list is copied into `R2APITVEController` components which are added on `CharacterBody.onBodyStartGlobal`. Hooks onto CharacterBody's `UpdateAllTemporaryVisualEffects()` and `UpdateSingleTemporaryVisualEffect` to update custom TVEs just like vanilla ones. Compares the latter method's `resourceString` input with the dictionary's string key in order to instantiate the correct TVE GameObject.
`AddTemporaryVisualEffect()` requires a CharacterBody input, bool output delegate parameter. This …
> Adding TempVisualEffectAPI

- R2API/DotAPI.cs
Fixes issue number #324, Simply checks if the BuffDef associated to the DOT exists, if not, continues adding it to the dot catalog as normal.
Debug.LogInfo message properly displays this change, with a new message that simply says "Custom Dot (Index: {dotDefIndex}) with no associated Buff added".
Also applied the same changes to the unrolled version, associatedBuff is now null by default and its not mandatory-
> Null checking the associated buff belonging to a DOT

- R2API/RecalculateStatsAPI.cs
Adds more things to RecalculateStatsAPI.
Currently the following:
Curse
Shield Multiplier
All manner of Cooldown Reduction
Flat Jump Power (someone probably has a use for this,somewhere)
Level Scaling (How much each level matters,rather than modifying the current level,since that can already be changed)
Root,the implementation of which might have been better,but I hope that the way it is ends up working well.
These are all seperate commits for convenience reasons.While I haven't tested them seperately all the commits should be buildable by themselves.
> RecalculateStatsAPI: Add Extra stat customization points.

- .github/workflows/release.yml
- R2API.sln
- thunderstore.toml
This PR allows the upload of a thunderstore package when a Github Release is made or when the action is manually triggered by an authorized user.
For this to work a repository secret must be added, called `TCLI_AUTH_TOKEN` which must contains the thunderstore api token delivered when completing the following : https://github.com/thunderstore-io/thunderstore-cli/wiki#authentication
> Thunderstore Release with GitHub Action

- R2API/ItemAPI.cs
- README.md
Some character mods have exported their model really tiny (or large) and this messes with default IDRS on those characters. The resulting default rulesets will blow up making the game unplayable when such an item is picked up.
So while those mods should really fix their model, it's a minor effort on our end to let them opt out of being assigned default rulesets.
(Also stops allocating memory bodyprefab * 2 * (items+equipment) times for `.name` and instead just is bodyprefab * 2 allocations)
> Allow default idrs opt out

- R2API/Utils/APISubmodule.cs
a modder could incorrectly have their attribute with a null parameter in it
fix https://github.com/risk-of-thunder/R2API/issues/315
> check if args are null for R2APISubmoduleDependency

- R2API/R2API.cs
Doesnt seem to be needed anymore, add extra init time and seems to be causing fps issue on some linux install https://github.com/risk-of-thunder/R2API/issues/314
> Don't use cecil backend for monomod

- R2API/RecalculateStatsAPI.cs
- README.md
Adds a crit damage modifier to RecalculateStatsAPI,since the newest update moved the relevant values from OnHit to the Body.
Also includes a quick fix to the documentation/summary comments on the shield modifiers, since they previously lacked a correct formula which has caused at least one case of someone misidentifying what shieldMultAdd does, my bad for missing that one last time.
> RecalculateStatsAPI: Shield Documentation Fix + New Crit Damage Modifier

- R2API/ContentManagement/ContentAddition.cs
- R2API/DifficultyAPI.cs
- R2API/EliteAPI.cs
- R2API/ItemAPI.cs
- R2API/ScriptableObjects/SerializableDifficultyDef.cs
A piece of code that was originally created on MSU, the SerializableDifficultyDef simply acts, as the name implies, as a Serializable version of DifficultyDef.
This can be used to pre-create difficultyDefs on thunderkit mods and then have them added by R2API's AddDifficulty() methods. The "finalized" difficultyDef is a property on the ScriptableObject and the DifficultyIndex can be obtained from another property on the ScriptableObject itself.
> Added SerializableDifficultyDef

- R2API/RecalculateStatsAPI.cs
Necessary but A Breaking Change nonetheless :(
Fixes #363
> RecalculateStatsAPI:critDamageMultAdd is now float , Fixes #363 

- R2API/ContentManagement/R2APIContentPackProvider.cs
- R2API/PrefabAPI.cs
- R2API/ScriptableObjects/ArtifactCode.cs
This PR fixes 2 issues.
1- Fixes issue #360, where the ArtifactCode's Vector3 rows where badly implemented.
2- Issue with how R2API logs the content of ContentPacks added to it, It'll no longer Log content multiple times.
> ArtifactCode fix, ContentLogging fix

- R2API/ItemAPI.cs
- README.md
Someone forgot to re-add the ItemDefinition/EquipmentDefinition adding when they changed ItemAPI to work with the new Contentpack system in R2API. This addresses that error, and fixes ItemDisplay registration as a result.
> Fix ItemDisplay issues in R2API SOTV

- R2API/ItemAPI.cs
This PR fixes issue #370. 
ItemAPI no longer checks if the pickup model prefab contains the ItemDisplay component, as in reality that prefab does not require said component, but instead checks the followerPrefab for the rules in the item/equipment's ItemDisplayDictionary.
The ItemDisplayDictionary now has a Validation method, the validation method does not prohibit the addition of a new item/equipment, instead, it's sole purpose is to ensure the Dictionary has valid ItemDisplayRules, the validation method logs the faulty rules using a string builder, which is later logged into the console using R2API.Logger.DebugLog().
The validator looks for:
ItemDisplayRules where the follower prefab is null
ItemDisplayRules where the follower prefab is not null, but does not have an ItemDisplay …
> ItemAPI ItemDisplay fixes

- R2API.Test/R2APITest.cs
- R2API.Test/Tests/AwakeTests/EliteAPITests.cs
- R2API/Director/DirectorAPIinternal.cs
- R2API/EliteAPI.cs
- Fix EliteAPI : Was not working anymore because we are calling the CombatDirector.Init and it fill the arrays with null references since we are not early loading the game content anymore, the easy fix is to early load those specific defs which makes the whole thing work again, this is not proper and ideally everything should probably happen inside a IContentPackProvider, I added a todo comment which talks about this a bit more.
- Add a test to verify if the EliteAPI works or not.
- Fix a null ref that could happen with old stages with DirectorAPI
> Fix EliteAPI and bug fix DirectorAPI

- R2API/Director/DirectorAPIexternal.cs
Sometimes, you want to let users specify internal stage names at runtime, and it's cleaner for R2API to handle this than reimplement it downstream or encourage checking `SceneDef.baseSceneName`.
> Friendlier internal stage names

- R2API/Utils/Reflection.cs
here is the benchmark
```
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19044.1620 (21H2)
Intel Core i7-4790 CPU 3.60GHz (Haswell), 1 CPU, 8 logical and 4 physical cores
[Host]   : .NET Framework 4.8 (4.8.4470.0), X64 RyuJIT
Mono x64 : Mono 6.12.0 (Visual Studio), X64 
Job=Mono x64  Runtime=Mono x64  
|                          Method |        Mean |     Error |     StdDev | Ratio | RatioSD |  Gen 0 | Allocated |
|-------------------------------- |------------:|----------:|-----------:|------:|--------:|-------:|----------:|
|                       DirectSet |   0.6177 ns | 0.0482 ns |  0.0427 ns | 0.002 |    0.00 |      - |         - |
|               FieldInfoSetValue | 297.2050 ns | 5.6635 ns |  5.0206 ns | 1.000 |    0.00 |      - |         - |
|             R2API.SetFieldValue | 227.2970 …
```
> Improve reflection utils speed  (#377)

- R2API.Test/Tests/AwakeTests/ReflectionTests.cs
- R2API/Utils/Reflection.cs
the previous algorithm resulted in the following hashcodes being equal
```cs
var hashcode1 = Reflection.CombineHashCode(new Type[]{typeof(string), typeof(int), typeof(string), typeof(int)});
var hashcode2 = Reflection.CombineHashCode(new Type[]{typeof(string), typeof(string), typeof(int), typeof(int)});
```
> Fix CombineHashCode return the same result on arrays of different order

- R2API/ItemAPI.cs
> specify idrs log is in the log file

- R2API/UnlockableAPI.cs
The reason behind these changes is due to the game's 1.2.3 release, which allows us modders to properly use the RegisterAchievement attribute on top of BaseAchievement inheriting classes.
The attribute itself in the game takes care of the registering of AchievementDefs and tying said Achievements to UnlockableDefs, as such, UnlockableAPI has become overall obsolete as the game now provides all the necesary means of registering UnlockableDefs, AchievementDefs and tying Achievements to Unlockables.
Each surface level type of unlockableAPI has been marked obsolete with the following message: 
The patch 1.2.3 for RoR2 has made UnlockableAPI's methods and implementations redundant
From now on use the Game's "RegisterAchievement" attribute on top of baseAchievement inheriting classes to …
> Marked UnlockableAPI as Obsolete

- R2API/ItemAPI.cs
Update 1.2.3 to Risk of Rain made the itemDef's "tier" into a property (Was originally a field). the Property's Set method causes issues when the itemTier catalog as not initialized yet (set method calls ItemTierCatalog.GetItemTierDef(itemTierEnum), and at that point no itemTierDefs exist in the catalog yet.) 
This update fixes this issue by doing the following check on the tierargument, while also adding a new optional argument (For itemTierDefs)
When the tier argument is not assignedAtRuntime, the ItemDef's _itemTierDef gets loaded via Addressables by doing a switch case on the given tier argument.
If the tier argument is assignedAtRuntime, but no itemTierDef is specified, R2API throws a warning that the itemDef has the tier argument to assignedAtRuntime, but itemTierDef argument is …
> ItemAPI tier fix

- R2API/Director/DirectorAPIhelpers.cs
Example code without `AddSelectedNewMonsters` or public `AddNewMonster`:
```cs
MonsterActions += (dccsPool, mixEnemyArtifactMonsters, currentStage) => {
DirectorCardHolder? monsterCardHolder;
monsterCardHoldersByStage.TryGetValue(currentStage.ToInternalStageName(), out monsterCardHolder);
if (monsterCardHolder is not null) {
bool addToFamilies = false;
if (dccsPool) {
ForEachPoolCategoryInDccsPool(dccsPool, (poolCategory) => {
var isNotAFamilyCategory = poolCategory.name != MonsterPoolCategories.Family;
var isAFamilyCategoryAndShouldAddToIt = addToFamilies && poolCategory.name == MonsterPoolCategories.Family;
if (isNotAFamilyCategory || isAFamilyCategoryAndShouldAddToIt) {
ForEachPoolEntryInDccsPoolCategory(poolCategory, (poolEntry) => {
AddMonsterToPoolEntry(monsterCardHolder, …
```
> Add `AddNewMonsterToStagesWhere` & `AddSelectedNewMonsters`, and publicize base `AddNewMonster`

- R2API/ContentManagement/R2APIContentManager.cs
- R2API/Utils/APISubmodule.cs
- R2API/Utils/CommandHelper.cs
- R2API/Utils/Reflection.cs
Sometimes assembly.GetTypes() can throw ReflectionTypeLoadException when some types cannot be loaded because of missing assembly dependencies for example, apis should still try to handle the types that were properly loaded and not completly die like CommandHelper was doing
> Handle ReflectionTypeLoadException

- R2API/DamageAPI.cs
Adds the GetModdedDamageTypeHolder family of public functions,which allows users to access all modded damage types for a given attack instance.
Previously this capability was only there for projectiles/things using ModdedDamageTypeHolderComponent).
> DamageAPI: Add public surface to access MDTHolders

- R2API.Director/DirectorAPIinternal.cs
Same as #424 but for the split assemblies branch
> Split-Assemblies branch: DirectorAPI: fix family dccs not being properly backed up / restored

- R2API.Legacy/TypeForwards.cs
- R2API.TempVisualEffect/README.md
- R2API.TempVisualEffect/TempVisualEffectAPI.cs
* Switches the component system to a dictionary and array pool to reduce GetComponent calls, should boost performance
* Added optional EffectRadius delegate to support any options past radius and bestFitRadius
* Removed unnecessary restrictions on adding TemporaryVisualEffects after content packs are loaded
* Update readme
I wasn't able to test these changes so hopefully nothing is too broken. Ideally they can be tested sometime before split assemblies release
> TempVisualEffectAPI changes

- R2API.Difficulty/DifficultyAPI.cs
- R2API.Difficulty/README.md
- R2API.Difficulty/thunderstore.toml
The vanilla implementation of `DifficultyCatalog.GetDifficultyDef()` was handling out of bounds indices and just return null. And lobby browser would (I assume) display default difficulty which is rainstorm.
R2API on the other hand was throwing an exception in such cases, but there's a catch, it all was executed in a not awaited Task, so any exception was just silent.
Logged stackTrace myself just out of curiosity:
<details>
<summary>StackTrace</summary>
[Error  :R2API.Difficulty]   at R2API.DifficultyAPI.GetExtendedDifficultyDef (On.RoR2.DifficultyCatalog+orig_GetDifficultyDef orig, RoR2.DifficultyIndex difficultyIndex) [0x00000] in <9a72a7ea04974316b97f295c869a8f3a>:IL_0000 
at DMD<>?503022336.Hook<RoR2.DifficultyCatalog::GetDifficultyDef>?-678958208 (RoR2.DifficultyIndex ) [0x00000] in …
> Fixed empty lobby browser

- R2API.sln
BuildCI is only involved in preparing a thunderstore release (which manually invokes it with `dotnet run` ) so having it within the normal build does nothing of benefit beyond erroring out compilation on LTS compilers.
> Remove BuildCI from build configurations.

- R2API.Elites/EliteRamp.cs
Value for shaderEliteRampIndex initializes to -1.
Supporting negatives in the existing check renders it equivalent to `if(x!=0) x = 0` ,at which point just setting it no matter what is more efficent.
> EliteAPI: Fix default/unset rampindex

- R2API.DamageType/DamageAPI.cs
- R2API.DamageType/README.md
- R2API.DamageType/thunderstore.toml
Addressing #460 
Previously wherever it was possible I was matching for NewObj and Stloc, and using index from Stloc to emit value later. There was no real reason to emit copy call later except that I thought it would be nice to have modded damage type assignment near vanilla damage type, which is unnecessary. But some other mods (for example `Hypercrit` and `MoreItems`) emitted Dup right after NewObj, which worked fine before the split because r2api was applying its hooks first, but with lazy init it can happen at any time.
Now `DamageAPI` will also use Dup after NewObj, with Goto only to NewObj, which should decrease the chances of something breaking with other mods hooking the same methods.
> DamageAPI fix

- R2API.RecalculateStats/README.md
- R2API.RecalculateStats/RecalculateStatsAPI.cs
- R2API.RecalculateStats/thunderstore.toml
Try saying that five times fast..Implements #406. An attack speed reduction value exists in vanilla exclusively for Light Flux Pauldron. Works the same as `moveSpeedReductionMultAdd` where `ATTACK_SPEED ~ (BASE_ATTACK_SPEED + baseAttackSpeedAdd) * (ATTACK_SPEED_MULT + attackSpeedMultAdd) / (ATTACK_SPEED_REDUCTION_MULT + attackSpeedReductionMultAdd)`. Seems to perform as expected through basic testing.
> attackSpeedReductionMultAdd for RecalculateStatsAPI

- R2API.DamageType/DamageAPI.cs
- R2API.DamageType/README.md
- R2API.DamageType/thunderstore.toml
Previous fix moved damageTypeHolder copy before damageInfo initialization for some projectile components
> Fix DamageAPI projectile hooks

- R2API.Core/README.md
- R2API.Core/Utils/CompressedFlagArrayUtilities.cs
- R2API.Core/thunderstore.toml
- R2API.DamageType/DamageAPI.cs
- R2API.DamageType/README.md
- R2API.DamageType/thunderstore.toml
Was there any need to? No. Did I do it anyways? Yes.
There is more optimization to be had in cases of 64+ reserved damage types (mainly memory efficiency), but I doubt we have that much even with deprecated mods, so it can wait for indefinite amount of time.
Changed a bit format of the data sent over network, compared to #284. Now:
* If there's 8 or less damage types reserved, only one byte will be sent. Purely flag values, no compression.
* If there's 64 or less damage types reserved, 1 section byte and 1-8 value bytes will be sent.
* Otherwise it's the same as in #284 except instead of 1-4 block part bytes and then 1-18 value bytes, now value bytes are written after each block part, i.e. 1 section byte [1 block part byte 1-6 value bytes] [1 block part byte 1-5 value bytes] 1 block part …
> CompressedFlagArrayUtilities optimization

- R2API.Core/AssemblyInfo.cs
- R2API.Loadout/LoadoutAPI.cs
- R2API.Loadout/R2API.Loadout.csproj
- R2API.Skins/IconTexJob.cs
- R2API.Skins/OverrideData.cs
- R2API.Skins/R2API.Skins.csproj
- R2API.Skins/README.md
- R2API.Skins/SkinDefInfo.cs
- R2API.Skins/SkinIDRS.cs
- R2API.Skins/Skins.cs
- R2API.Skins/SkinsPlugin.cs
- R2API.Skins/thunderstore.toml
- R2API.sln
This Pull request changes 2 Submodules.
The main new change is the Skins submodule, which is basically an "extraction" of LoadoutAPI's Skin features, including the Sprite creation job, the SkinDefInfo struct, ETC.
The other change is completely deprecating LoadoutAPI, LoadoutAPI's methods now mostly just use either ContenttManagement's ContentAddition class, and it's Skin related systems have been salvaged to the new Submodule, Skins.
LoadoutAPI's SkinDefInfo struct now has an implicit operator for Skins submodule's SkinDefInfo, which with my tests have proved that this new submodule change wont break mods, as I've also added the Skins submodule to LoadoutAPI's dependencies.
Apart from using LoadoutAPI's skin systems, the Skin submodule also now comes with Skin Specific IDRS replacements. …
> Skins Submodule

- R2API.Director/DirectorAPIexternal.cs
- R2API.Director/README.md
- R2API.Director/thunderstore.toml
The original code for DirectorAPI has this set to their methods that parse a Stage's name to a Stage Enum, and for StageEnum to StageName.
```
Stage.VoidLocus => "voidraid",
Stage.ThePlanetarium => "voidstage",
```
```
"voidraid" => Stage.VoidLocus,
"voidstage" => Stage.ThePlanetarium,
```
This of course is wrong, as the enum and names point to the wrong values, VoidLocus should point to voidstage and ThePlanetarium should point to voidraid`
i'm doing this change as this was an upstream issue on teammoonstorm/starstorm2#271
> Fix VoidLocus & ThePlanetarium accidental swap

- .github/workflows/release.yml
- locally_verify_release_ci.sh
fix ci breaking due to https://github.com/risk-of-thunder/R2API/commit/d55e9064676aeb296dc6a17198f4fe4a4182553a#diff-6695f846f6d9db6b084e118db68d388645a92cd133bdf1651454121f93bc2123R17 
and not running as Release config
> fix ci breaking

- R2API.Legacy/R2API.Legacy.csproj
- R2API.Legacy/thunderstore.toml
R2API.Legacy has a projectref to R2API.Loadout, R2API.Loadout has a Private=false reference to R2API.Skins, but that somehow make R2API.Skins getting outputted to output build folder even though it's not referenced anywhere???
> Fix R2API.Skins being shipped with the legacy package for some reason

- R2API.Addressables/AddressReferencedAssets/AddressReferencedAsset.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedBuffDef.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedEliteDef.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedEquipmentDef.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedExpansionDef.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedItemDef.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedPrefab.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedSpawnCard.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedUnlockableDef.cs
- R2API.Addressables/AddressablesPlugin.cs
- R2API.Addressables/R2API.Addressables.csproj
- R2API.Addressables/README.md
- R2API.Addressables/thunderstore.toml
- R2API.Director/AddressableDCCSPool.cs
- R2API.Director/AddressableDirectorCard.cs
- R2API.Director/AddressableDirectorCardCategorySelection.cs
- R2API.Director/DirectorAPIexternal.cs
- R2API.Director/DirectorPlugin.cs
- R2API.Director/README.md
- R2API.Director/thunderstore.toml
- R2API.sln
The addressables submodule should ideally contain all the addressables utility, this addressable utility is usually miscelaneous, but currently pertrains Editor and Runtime functionality.
Currently it contains the [AddressableAsset](https://github.com/TeamMoonstorm/MoonstormSharedUtils/blob/main/Runtime/Code/Classes/AddressableAsset/AddressableAsset.cs) system from MoonstormSharedUtils. but rebranded as "AddressReferencedAsset"
The AddressReferencedAsset is a wrapper for an Asset that can be either specified explicitly (set in the editor or at runtime manually), or specified implicitly via an address (set in the editor or at runtime). including different utilities such as implicit operators and constructors. Some of these classes have the ability to load the asset using Catalogs, the …
> Addressables submodule and DirectorAPI additions

- R2API.Core/Utils/DirectMessage.cs
-  Removed extra space on lines 13 and 16
Just a small thing I noticed while looking through the code.
> Remove extra spaces in DirectMessage's documentation comments

- R2API.Core/README.md
- R2API.Core/Utils/SystemInitializerInjector.cs
- R2API.Core/thunderstore.toml
Fixes #502
This implementation also accounts for there being multiple SystemInitializer methods in the same class (not the case anywhere in game code, but thought it wouldn't hurt to handle that anyway).
> Fix SystemInitializerInjector

- R2API.Skins/README.md
- R2API.Skins/SkinVFX.cs
- R2API.Skins/SkinVFXHelpers.cs
- R2API.Skins/SkinVFXInfo.cs
- R2API.Skins/SkinsPlugin.cs
- R2API.Skins/thunderstore.toml
Adds the SkinVFX class to R2API.Skins. Provides an easy helper method for automatically replacing VFX depending on the equipped skin.
Supports replacing VFX for:
- EffectManager.SimpleMuzzleFlash
- BasicMeleeAttack swingEffectPrefab
- BulletAttack tracerEffectPrefab
- GenericDamageOrb's orb effect
- Any other spawned VFX if the source passes in the Identifier manually.
Provides the AddSkinVFX method, which takes in a SkinDef to require, any of (EffectIndex | string | GameObject), and either a replacement gameobject or a delegate to call upon the effect being spawned.
> Add support for skin-specific VFX replacements to the R2API.Skins submodule.

- R2API.Core/README.md
- R2API.Core/Utils/CompressedFlagArrayUtilities.cs
- R2API.Core/thunderstore.toml
- R2API.DamageType/DamageAPI.cs
- R2API.DamageType/README.md
- R2API.DamageType/thunderstore.toml
Not being able to support modded damage types made CrocoDamageTypeController almost entirely useless for mods and made compatibility between mods adding new passives to Acrid difficult.
However it's conceptually really useful,so here is an effort to make it work like we'd want it to.Includes additions to CompressedFlagArrayUtilities to facilitate non-destructive copying of ModdedDamageTypeHolders
Draft PR currently only implements support for projectiles,putting it up to gather feedback on changes to API surface and on the following:
The transfer of modded damage types from the holder assigned to the CrocoDamageTypeController needs to be deferred due to the way the vanilla component is setup (which is why it was such a pain),signalling for this is available through the remaining unused …
> CrocoDamageTypeController Support For DamageAPI

- R2API.Skins/README.md
- R2API.Skins/SkinIDRS.cs
- R2API.Skins/thunderstore.toml
Made `AddGroupOverrided` method which allows item developers to add skin-speific item displays without requiring to make full IDRS, because that's too much and wouldn't work if multiple mods tried to do that.
If there was added skin-spercific idrs the override will go on top of it, otherwise a clone of idrs from body prefab will be used as a base.
Also now storing idrs for each skin, to fix the issue where if you first applied a skin with idrs and then a skin without idrs and characterModel would keep using first skin idrs instead of default one (probably never comes up anywhere outside of IDRS helper, but it was annoying me).
> Skin-specific DisplayGroupRule overrides

- R2API.Dot/DotAPI.cs
- R2API.Dot/README.md
- R2API.Dot/thunderstore.toml
Update the active custom dots the moment one is inflicted, else it doesn't count for Death Mark until it has ticked once and its active state is refreshed in the FixedUpdate hook.
> Fix custom DOTs not counting as active upon infliction

- R2API.TempVisualEffect/README.md
- R2API.TempVisualEffect/thunderstore.toml
Closes https://github.com/risk-of-thunder/R2API/issues/538
> fix(TempVisualEffect): recompile needed cause RoR2.FixedSizeArrayPool.Return signature changed when sots dlc2 released

- R2API.Colors/ColorsAPI.cs
- R2API.Colors/README.md
- R2API.Colors/thunderstore.toml
I can only assume the real issue is JIT in Unity 2021 being very agressive with optimizations for dynamically generated methods (hooks in our case) when accessing static readonly arrays.
From debugging and logging it seems to me that a hook refers to a specific object ptr instead of a field. Adding new color creates new array and the hook still using old array which eventually gets deallocated and the hook returns random data.
Only making a hook, works fine. Only adding new colors to an array works fine. But doing both results in wrong results. A happy accident that it doesn't cause a crash, just because these methods don't use actual array length and instead uses enum value.
Probably propper solution would be making a patcher that would remove readonly modificator from these fields to …
> Fix ColorsAPI

- R2API.Colors/ColorsAPI.cs
- R2API.Colors/README.md
- R2API.Colors/thunderstore.toml
Not calling orig bit me, as it does. Some mods also hook into GetColors and some (namely Augmentum) don't modify indexToColor array but do their own stuff. To get back previous behaviour we just call static method in IL hook and return.
> ColorsAPI IL instead of On hook

- R2API.Elites/EliteAPI.cs
https://store.steampowered.com/news/app/632360/view/4478359995220492415
https://github.com/xiaoxiao921/RoR2_diff_20_05_2024/blame/2b1da2d/DecompilationOutput/RoR2/CombatDirector.cs#L516
https://github.com/xiaoxiao921/RoR2_diff_20_05_2024/blame/2b1da2d/DecompilationOutput/RoR2/CombatDirector.cs#L498
Past stage two, elite cost uses the old reduced *Honor* value otherwise (with this **API** installed). They also added an extra check that, while unnecessary, is included.
> EliteAPI: Update conditional cost to match latest game version

- R2API.RecalculateStats/README.md
- R2API.RecalculateStats/RecalculateStatsAPI.cs
- R2API.RecalculateStats/thunderstore.toml
Allows modders to add bleed chance on top of that granted by daggers and thorn. I've tested it with my own mod and it is able to handle multiple different modded items adding bleed chance at once, as well as bleed chance past 100.
> Add bleed chance to stats API

- R2API.Skills/README.md
- R2API.Skills/SkillsAPI.cs
- R2API.Skills/thunderstore.toml
ConcentricContent was hooking the same place breaking our goto. Made it less specific.
> [R2API.Skils] Fix mod incompatibility

- R2API.ContentManagement/R2APISerializableContentPack.cs
- R2API.ContentManagement/README.md
- R2API.ContentManagement/thunderstore.toml
`ContentAddition.AddItemRelationshipProvider` isn't functional because it never adds the object to the `ContentPack.itemRelationshipProviders` from the `R2APISerializableContentPack.itemRelationshipProviders`
> [ContentManagement] Fix for ItemRelationshipProviders

- R2API.ContentManagement/ContentAddition.cs
- R2API.ContentManagement/R2APISerializableContentPack.cs
- R2API.ContentManagement/README.md
- R2API.ContentManagement/thunderstore.toml
ItemDef.Pair cant contain null itemdefs because GetHashCode explodes
- ContentAddition rejects providers that have a null relationshipType or relationship fields
- R2APISerializableContentPack sanitizes the relationship array before adding to the contentpack
> [ContentManagement] Added Rejection cases and null check fields

- R2API.DamageType/DamageAPI.cs
- R2API.DamageType/README.md
- R2API.DamageType/thunderstore.toml
Surprise, surprise, even mods like StarStorm forget to register damage types. I would still prefer the exception but completely breaking existing mods is not good.
> [DamageAPI] Changed bounds exception to just log error to not completely break mods that already try to use not registered damage types.

- R2API.Animations/R2API.Animations.csproj
Forgot that for pipeline to build not referenced project you need to add project reference but without referencing assembly
> [AnimationsAPI] fix auto build

- R2API.Director/DirectorAPIhelpers.cs
- R2API.Director/README.md
- R2API.Director/thunderstore.toml
With `DccsBlender` in play, adding monsters and interactables to every `DirectorCardCategorySelection` would result in cards being added to the spawn pools up to 3 times (since by default the system mixes `Always Included` DCCS plus two from `Included If Conditions Met`). Ideally we should only add new cards to DCCS under `Always Included`, however Gearbox break their own rule and some Simulacrum stages only have `Included if No Conditions Met` DCCS.
> Fixed custom monsters and interactables being added to stage pool multiple times as a result of SoTS Phase 2 changes

- R2API.ContentManagement/ContentManagementPlugin.cs
- R2API.ContentManagement/GameModeFixes.cs
- R2API.ContentManagement/GameModeInfo.cs
- R2API.ContentManagement/README.md
- R2API.ContentManagement/thunderstore.toml
* Adds fixes for modded Game Modes not showing up in the multiplayer menu
* Adds sorting for Game Modes to display them in the proper order (modded modes after vanilla)
* Adds new class `GameModeInfo` for modders to add to their GameMode prefab
* Adds automatic button addition to the "Alternate GameModes" screen
> ContentAddition 1.0.9 GameMode Support

- R2API.RecalculateStats/README.md
- R2API.RecalculateStats/RecalculateStatsAPI.cs
- R2API.RecalculateStats/thunderstore.toml
To quote my initial pitch:
>I'm wondering if anybody is opposed to RecalculateStats having a new field for all of "main" stats to allow for multiplicative stacking. Something like this is not present, and has to be replicated like how vanilla does it (Growth Nectar, Tonic, Weak) by IL hooking.
>
>Using health an example, it would come with a new field "healthTotalMult" that defaults to 1f instead of 0f,  with the intention being that you multiply the value - instead of adding to it - by your custom multiplier. Then, at the same point in the base RecalculateStats that grectar and tonic are done, we would apply the accumulated multiplier. So the health formula becomes (BASE_HEALTH + baseHealthAdd + levelHealthAdd * levelMultiplier) * (HEALTH_MULT + healthMultAdd) * healthTotalMult.
The …
> Added multiplicative stat modifiers.

- R2API.Addressables/AddressReferencedAssets/AddressReferencedAsset.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedBuffDef.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedEliteDef.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedEquipmentDef.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedExpansionDef.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedItemDef.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedUnlockableDef.cs
- R2API.Addressables/AddressablesPlugin.cs
- R2API.Addressables/README.md
- R2API.Addressables/thunderstore.toml
* Implemented the ability to restrict a load to not use the ingame catalogs, forcing an address to be used instead.
* implemented IDisposeable an AddressReferencedAsset, which releases an internal handle for the addressable asset.
* Added the ability to bypass the secure loading by calling ResolveAsset().
* Replaced most of the Task returning methods with IEnumerator coroutines.
> R2API.Addressables revamp and improvements

- R2API.Dot/DotAPI.cs
- R2API.Dot/README.md
- R2API.Dot/thunderstore.toml
Adds CustomDotDamageEvaluation delegate to custom dots to run their own damage evaluations. 
In this example Irradiated DOT is running Blast Attack to damage not only the victim, but also its nearby allies.
```
public static void IrradiatedDotEvaluation(DotController self, DotController.PendingDamage pendingDamage)
{
BlastAttack blastAttack = new BlastAttack
{
attacker = pendingDamage.attackerObject,
inflictor = pendingDamage.attackerObject,
teamIndex = TeamComponent.GetObjectTeam(pendingDamage.attackerObject),
baseDamage = pendingDamage.totalDamage,
baseForce = 0f,
position = self.victimBody.corePosition,
radius = irradiatedRadius,
damageColorIndex = DamageColorIndex.Nearby,
falloffModel = BlastAttack.FalloffModel.None,
};
blastAttack.Fire();
EffectData effectData = new EffectData
{ …
```
> CustomDotDamageEvaluation feature to Dot API

- R2API.Skills.Interop/SkillDefInterop.cs
- R2API.Skills.Patcher/SkillsPatcher.cs
- R2API.Skills/README.md
- R2API.Skills/SkillsAPI.cs
- R2API.Skills/thunderstore.toml
- RoR2.Patched/SkillDef.cs
Adds a feature to set custom cooldown refresh sound instead of default "Play_UI_cooldownRefresh" if it is not null.
Set and get custom cooldown refresh sound field with `SetCustomCooldownRefreshSound` and `GetCustomCooldownRefreshSound` respectfully.
Small showcase: https://github.com/user-attachments/assets/4ff97a2c-3ac9-4938-b60d-e054d7f6688b
> R2API.Skills CustomCooldownRefreshSound feature

- R2API.Core/AssemblyInfo.cs
- R2API.Core/R2API.cs
- R2API.Core/README.md
- R2API.Core/Utils/EnumPatcher.cs
- R2API.Core/thunderstore.toml
- R2API.Teams.Interop/R2API.Teams.Interop.csproj
- R2API.Teams.Interop/TeamsInterop.cs
- R2API.Teams.Patcher/R2API.Teams.Patcher.csproj
- R2API.Teams.Patcher/TeamsPatcher.cs
- R2API.Teams/Log.cs
- R2API.Teams/R2API.Teams.csproj
- R2API.Teams/README.md
- R2API.Teams/TeamsAPI.cs
- R2API.Teams/TeamsAPINetworkExtensions.cs
- R2API.Teams/TeamsPlugin.cs
- R2API.Teams/thunderstore.toml
- R2API.sln
- RoR2.Patched/TeamMask.cs
Allows for addition of modded Teams.
There is a hard limit of how many teams can be added due to TeamIndex being backed by an sbyte, though this limit is 121 with the current amount of vanilla teams, so it really shouldn't be an issue. There is potential to double the team limit by using the negative values of TeamIndex (-128 ... -2), though this would require significant patching for proper overflow handling, so I didn't deem it necessary for now.
For compatibility purposes, EnumPatcher allows Enum.Parse/ToString/GetValues/GetNames/etc. to use modded TeamIndex entries as if they were vanilla ones.
I figured other modules could also make use of the EnumPatcher in the future, so it's in Core rather than Teams, so this does require a version bump of R2API.Core.
> R2API.Teams submodule

- R2API.Addressables/AddressReferencedAssets/AddressReferencedAsset.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedBuffDef.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedEliteDef.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedEquipmentDef.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedExpansionDef.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedItemDef.cs
- R2API.Addressables/AddressReferencedAssets/AddressReferencedUnlockableDef.cs
- R2API.Addressables/AddressablesPlugin.cs
- R2API.Addressables/README.md
- R2API.Director/AddressableDCCSPool.cs
- R2API.Director/AddressableDirectorCardCategorySelection.cs
- R2API.Director/README.md
- R2API.Director/thunderstore.toml
This is a proper fix for 1.1.0 after coming back from PAX WEST.
This has been tested against a 350+ mod profile with multiple different mods that may use both the director plugin and the addressables plugin. No major issues where spotted during testing.
The intense log spam reported by one of the members of the modcord has been fixed, it was caused by a run-away call of the onAddressablesAssetsInitialized event being called multiple times.
----
For the director, i've proceeded to unwind the LINQ calls into proper calls that should fail gracefully if something goes wrong, for example, even if an old map tries to load the old cscBeetle using its old path address, it will fail to add it to the dccs but it wont crash the game.
> Fix Addressables submodule's 1.1.0 being completely broken
